version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - KEYCLOAK_URL=http://lot-sanmateo-keycloak:8080/realms/lot-sanmateo
      - KEYCLOAK_CLIENT_ID=lot-sanmateo-client
      - CUSTOMER_API_URL=http://host.docker.internal:8080/
      - KEYCLOAK_REQUIRED_ROLE=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sanmateo-network

networks:
  sanmateo-network:
    external: true
    name: be-lotsanmateo_sanmateo-network
